[05 线性代数【动手学深度学习v2】](https://www.bilibili.com/video/BV1eK4y1U7Qy?spm_id_from=333.999.0.0)

### 自动求导
- 假设想对$y = 2x^Tx$ 关于列向量x求导

In [1]:
import torch
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [2]:
# 计算y关于x的梯度之前，我们需要一个地方来储存梯度。
# 可以通过x.grad获得x的梯度
x.requires_grad_(True)

tensor([0., 1., 2., 3.], requires_grad=True)

In [3]:
x.grad

In [4]:
y = 2*torch.dot(x,x)
y
# 此处的grad_function指明y属于从x计算过来的

tensor(28., grad_fn=<MulBackward0>)

In [5]:
# 调用反向传播来自动计算y关于x每个分量的梯度
# y = 2x2 y'=4x
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [6]:
x.grad == 4*x

tensor([True, True, True, True])

- 默认情况下。pytorch会累积梯度，我们需要清除之前的值

In [7]:
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

- 深度学习中，我们的目的不是计算微分矩阵，而是批量中每个样本单独计算的偏导数之和

In [8]:
# 这里是一个标准的函数求导方法
# 对非标量调用backward需要传入一个gradient参数，该参数指定微分函数
x.grad.zero_()
y = x*x
# y.backward(torch.ones(len(x)))
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [9]:
x.grad.zero_()
y = torch.dot(x,x)
y.backward()
x.grad

tensor([0., 2., 4., 6.])

In [10]:
x.grad.zero_()
y = x*x
# 此处相当于将y转换成一个常数
u = y.detach()
z = u*x
z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [11]:
x.grad.zero_()
y.sum().backward()
x.grad == 2*x

tensor([True, True, True, True])

- 控制流
- 其实就是我们常见的操作
- 顺序控制流 if else
- 分支控制流 if elif else
- 循环控制流 while for continue break

In [12]:
# 这里想说明的是对于控制流，依然可以计算得到的变量的梯度
def f(a):
    b = a*2
    # norm是2范数
    while b.norm()<1000:
        b = b*2
    if b.sum()>0:
        c = b
    else:
        c = 100*b
    return c
# a为随机数
a = torch.randn(size = (),requires_grad=True)
d = f(a)
d.backward()
a.grad,d,a,d/a


(tensor(4096.),
 tensor(1998.3901, grad_fn=<MulBackward0>),
 tensor(0.4879, requires_grad=True),
 tensor(4096., grad_fn=<DivBackward0>))