[22 池化层](https://www.bilibili.com/video/BV1EV411j7nX?spm_id_from=333.999.0.0)

- 我们在处理图像的时候，希望输出的结果具有一定的处理平移能力，比如物体出现了小范围的移动，那么要有能力依旧检测出来
- 池化层有利于缓解卷积层对于位置的敏感性
- 最大池化层可以一定程度上做到这一点
- 池化层同样具有步幅和填充，但是因为没有卷积核，所以不需要学习参数
- 池化层有取最大值和取平均值两种方法

In [ ]:
import torch
from torch import nn
from d2l import torch as d2l

In [56]:
# 池化层的正向传播，简单粗暴
def pool2d(X, pool_size, mode='max'):
    p_h, p_w = pool_size
    Y = torch.zeros((X.shape[0] - p_h + 1, X.shape[1] - p_w + 1))
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            if mode == 'max':
                Y[i, j] = X[i: i + p_h, j: j + p_w].max()
            elif mode == 'avg':
                Y[i, j] = X[i: i + p_h, j: j + p_w].mean()
    return Y

In [57]:
X = torch.tensor([[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]])
pool2d(X, (2, 2))

tensor([[4., 5.],
        [7., 8.]])

In [58]:
pool2d(X, (2, 2), 'avg')

tensor([[2., 3.],
        [5., 6.]])

In [59]:
X = torch.arange(16, dtype=d2l.float32).reshape((1, 1, 4, 4))
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]]]])

In [60]:
# 深度学习框架中的池化层，同样可以指定步幅和填充
pool2d_nn = nn.MaxPool2d(kernel_size=3,stride=2,padding=1)
pool2d_nn(X)

tensor([[[[ 5.,  7.],
          [13., 15.]]]])

In [61]:
pool2d_nn = nn.MaxPool2d((2, 3), padding=(1, 1), stride=(2, 3))
pool2d_nn(X)

tensor([[[[ 1.,  3.],
          [ 9., 11.],
          [13., 15.]]]])

### 多个通道池化
- 在处理多通道输⼊数据时，汇聚层在每个输⼊通道上单独运算，而不是像卷积层⼀样在通道上对输⼊进⾏汇
总。
- 这意味着汇聚层的输出通道数与输⼊通道数相同。
- 下⾯，我们将在通道维度上连结张量X 和X + 1，以
构建具有2 个通道的输⼊。

In [62]:
X = torch.cat((X, X + 1), 1)
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]],

         [[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.],
          [13., 14., 15., 16.]]]])

In [63]:
pool2d_nn = nn.MaxPool2d(3, padding=1, stride=2)
pool2d_nn(X)

tensor([[[[ 5.,  7.],
          [13., 15.]],

         [[ 6.,  8.],
          [14., 16.]]]])

### Q/A
- 池化层有两个作用：1、降低位置敏感性。2、降低计算量
- 然而现在可以通过调整卷积步幅来降低计算量
- 此外现在对图像本身会做很多增强处理，也降低了位置敏感性
- 所以池化层目前应用是逐渐减少的