补充知识：torch中permute()函数用法

In [73]:
import torch

In [74]:
x = torch.linspace(1, 60, steps=60).view(3,4,5)
print(x.size())
print(x)

torch.Size([3, 4, 5])
tensor([[[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.],
         [11., 12., 13., 14., 15.],
         [16., 17., 18., 19., 20.]],

        [[21., 22., 23., 24., 25.],
         [26., 27., 28., 29., 30.],
         [31., 32., 33., 34., 35.],
         [36., 37., 38., 39., 40.]],

        [[41., 42., 43., 44., 45.],
         [46., 47., 48., 49., 50.],
         [51., 52., 53., 54., 55.],
         [56., 57., 58., 59., 60.]]])


1与2交换,每一块的行与列进行交换，即每一块做转置行为

In [75]:
print(x.permute(0,2,1).size()) # 1与2交换,每一块的行与列进行交换，即每一块做转置行为
print(x.permute(0,2,1))
x.reshape(3,5,4)

torch.Size([3, 5, 4])
tensor([[[ 1.,  6., 11., 16.],
         [ 2.,  7., 12., 17.],
         [ 3.,  8., 13., 18.],
         [ 4.,  9., 14., 19.],
         [ 5., 10., 15., 20.]],

        [[21., 26., 31., 36.],
         [22., 27., 32., 37.],
         [23., 28., 33., 38.],
         [24., 29., 34., 39.],
         [25., 30., 35., 40.]],

        [[41., 46., 51., 56.],
         [42., 47., 52., 57.],
         [43., 48., 53., 58.],
         [44., 49., 54., 59.],
         [45., 50., 55., 60.]]])


tensor([[[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.],
         [13., 14., 15., 16.],
         [17., 18., 19., 20.]],

        [[21., 22., 23., 24.],
         [25., 26., 27., 28.],
         [29., 30., 31., 32.],
         [33., 34., 35., 36.],
         [37., 38., 39., 40.]],

        [[41., 42., 43., 44.],
         [45., 46., 47., 48.],
         [49., 50., 51., 52.],
         [53., 54., 55., 56.],
         [57., 58., 59., 60.]]])

0与1交换 交换块和行

In [76]:
print(x.permute(1,0,2).size()) 
print(x.permute(1,0,2)) 
x.reshape(4,3,5)

torch.Size([4, 3, 5])
tensor([[[ 1.,  2.,  3.,  4.,  5.],
         [21., 22., 23., 24., 25.],
         [41., 42., 43., 44., 45.]],

        [[ 6.,  7.,  8.,  9., 10.],
         [26., 27., 28., 29., 30.],
         [46., 47., 48., 49., 50.]],

        [[11., 12., 13., 14., 15.],
         [31., 32., 33., 34., 35.],
         [51., 52., 53., 54., 55.]],

        [[16., 17., 18., 19., 20.],
         [36., 37., 38., 39., 40.],
         [56., 57., 58., 59., 60.]]])


tensor([[[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.],
         [11., 12., 13., 14., 15.]],

        [[16., 17., 18., 19., 20.],
         [21., 22., 23., 24., 25.],
         [26., 27., 28., 29., 30.]],

        [[31., 32., 33., 34., 35.],
         [36., 37., 38., 39., 40.],
         [41., 42., 43., 44., 45.]],

        [[46., 47., 48., 49., 50.],
         [51., 52., 53., 54., 55.],
         [56., 57., 58., 59., 60.]]])

0与2交换 交换块和列

In [77]:
print(x.permute(2,1,0).size()) 
print(x.permute(2,1,0)) 
x.reshape(5,4,3)

torch.Size([5, 4, 3])
tensor([[[ 1., 21., 41.],
         [ 6., 26., 46.],
         [11., 31., 51.],
         [16., 36., 56.]],

        [[ 2., 22., 42.],
         [ 7., 27., 47.],
         [12., 32., 52.],
         [17., 37., 57.]],

        [[ 3., 23., 43.],
         [ 8., 28., 48.],
         [13., 33., 53.],
         [18., 38., 58.]],

        [[ 4., 24., 44.],
         [ 9., 29., 49.],
         [14., 34., 54.],
         [19., 39., 59.]],

        [[ 5., 25., 45.],
         [10., 30., 50.],
         [15., 35., 55.],
         [20., 40., 60.]]])


tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.],
         [10., 11., 12.]],

        [[13., 14., 15.],
         [16., 17., 18.],
         [19., 20., 21.],
         [22., 23., 24.]],

        [[25., 26., 27.],
         [28., 29., 30.],
         [31., 32., 33.],
         [34., 35., 36.]],

        [[37., 38., 39.],
         [40., 41., 42.],
         [43., 44., 45.],
         [46., 47., 48.]],

        [[49., 50., 51.],
         [52., 53., 54.],
         [55., 56., 57.],
         [58., 59., 60.]]])