torch.unsqueeze()这个函数主要是对数据维度进行扩充。给指定位置加上维数为一的维度，比如原本有个三行的数据（3），在0的位置加了一维就变成一行三列（1,3）。a.squeeze(N) 就是在a中指定位置N加上一个维数为1的维度。还有一种形式就是b=torch.squeeze(a，N) a就是在a中指定位置N加上一个维数为1的维度

In [18]:
import torch
x = torch.Tensor([1, 2, 3, 4])  # torch.Tensor是默认的tensor类型（torch.FlaotTensor）的简称。

print(x)  # tensor([1., 2., 3., 4.])
print(x.size())  # torch.Size([4])
print(x.dim())  # 1 查看tensor的维度，这里x是一维
print(x.numpy())  # [1. 2. 3. 4.]#将tensor数据转化为numpy形式

tensor([1., 2., 3., 4.])
torch.Size([4])
1
[1. 2. 3. 4.]


In [19]:
print(torch.unsqueeze(x, 0))  # tensor([[1., 2., 3., 4.]])
print(torch.unsqueeze(x, 0).size())  # torch.Size([1, 4])
print(torch.unsqueeze(x, 0).dim())  # 2
print(torch.unsqueeze(x, 0).numpy())  # [[1. 2. 3. 4.]]

tensor([[1., 2., 3., 4.]])
torch.Size([1, 4])
2
[[1. 2. 3. 4.]]


In [20]:
print(torch.unsqueeze(x, 1))

tensor([[1.],
        [2.],
        [3.],
        [4.]])


In [21]:
print(torch.unsqueeze(x, 1).size())  # torch.Size([4, 1])
print(torch.unsqueeze(x, 1).dim())  # 2

torch.Size([4, 1])
2


In [22]:
print(torch.unsqueeze(x, -1))

tensor([[1.],
        [2.],
        [3.],
        [4.]])


In [23]:
print(torch.unsqueeze(x, -1).size())  # torch.Size([4, 1])
print(torch.unsqueeze(x, -1).dim())  # 2

torch.Size([4, 1])
2


文中的逻辑复现一遍

In [24]:
from torch import nn

In [25]:
key_size=2
query_size=20
num_hiddens=8
W_k = nn.Linear(key_size, num_hiddens, bias=False)
W_q = nn.Linear(query_size, num_hiddens, bias=False)

In [26]:
queries, keys = torch.normal(0, 1, (2, 3, 20)), torch.ones((2, 10, 2))
queries.shape,keys.shape

(torch.Size([2, 3, 20]), torch.Size([2, 10, 2]))

In [27]:
queries = W_q(queries)
keys = W_k(keys)

In [28]:
queries.shape,keys.shape

(torch.Size([2, 3, 8]), torch.Size([2, 10, 8]))

In [29]:
queries = queries.unsqueeze(dim=2)
keys = keys.unsqueeze(dim=1)

可以看到unsqueeze对其指定的dim进行了升维

In [30]:
queries.shape,keys.shape

(torch.Size([2, 3, 1, 8]), torch.Size([2, 1, 10, 8]))

可以看出其以广播的形式相加

In [31]:
(queries+keys).shape

torch.Size([2, 3, 10, 8])

In [32]:
w_v = torch.tanh(queries+keys)

batch_size，查询的个数，“键－值”对的个数，num_hidden

In [33]:
w_v.shape

torch.Size([2, 3, 10, 8])