- torch.repeat
- 使张量沿着某个维度进行复制, 并且不仅可以复制张量，也可以拓展张量的维度:

In [42]:
import torch

x = torch.randn(2, 4)

# 1. 沿着某个维度复制
x.repeat(1, 1).size()  ,x.repeat(2, 1).size()  ,x.repeat(1, 2).size()

(torch.Size([2, 4]), torch.Size([4, 4]), torch.Size([2, 8]))

In [43]:
# 2. 不仅可以复制维度, 还可以拓展维度
x.repeat(1, 1, 1).size()  ,x.repeat(2, 1, 1).size()  ,x.repeat(1, 1, 1, 1).size()  

(torch.Size([1, 2, 4]), torch.Size([2, 2, 4]), torch.Size([1, 1, 2, 4]))

In [44]:
# 3. repeat中传入的参数不可以少于x的维度
# x.repeat(1)  # 报错

torch.repeat_interleave


torch.repeat_interleave的行为与numpy.repeat类似，但是和torch.repeat不同，这边还是以代码为例:

In [45]:
x = torch.randn(2, 2)
x

tensor([[-0.2580,  0.2197],
        [-2.1634, -0.3043]])

In [46]:
x.repeat(2, 1)

tensor([[-0.2580,  0.2197],
        [-2.1634, -0.3043],
        [-0.2580,  0.2197],
        [-2.1634, -0.3043]])

In [47]:
x.repeat_interleave(2, dim=0)

tensor([[-0.2580,  0.2197],
        [-0.2580,  0.2197],
        [-2.1634, -0.3043],
        [-2.1634, -0.3043]])

In [48]:
x.repeat_interleave(2, dim=1)

tensor([[-0.2580, -0.2580,  0.2197,  0.2197],
        [-2.1634, -2.1634, -0.3043, -0.3043]])

In [49]:
# 如果不传dim参数, 则默认复制后拉平
x.repeat_interleave(2)

tensor([-0.2580, -0.2580,  0.2197,  0.2197, -2.1634, -2.1634, -0.3043, -0.3043])

从这个代码可以看出来torch.repeat更像是把tensor作为一个整体进行复制, 
- 而torch.repeat_interleave更是针对tensor里的每个元素进行复制，
- 并且torch.repeat_interleave可以通过传入一个一维的torch.Tensor来指定每个元素复制的次数

In [50]:
x = torch.tensor([[1, 2], [3, 4]])
torch.repeat_interleave(x, torch.tensor([1, 3]), dim=0)

tensor([[1, 2],
        [3, 4],
        [3, 4],
        [3, 4]])

torch.tile
- torch.tile函数也是元素复制的一个函数, 但是在传参上和torch.repeat不同，但是也是以input为一个整体进行复制, torch.tile如果只传入一个参数的话, 默认是沿着行进行复制

In [51]:
x = torch.tensor([[1, 2], [3, 4]])

In [52]:
x.tile((2, )),x.repeat(1, 2)

(tensor([[1, 2, 1, 2],
         [3, 4, 3, 4]]),
 tensor([[1, 2, 1, 2],
         [3, 4, 3, 4]]))

torch.tile传入一个元组的话, 表示(行复制次数, 列复制次数)

In [53]:
x = torch.tensor([[1, 2], [3, 4]])
x.tile((2, 2))

tensor([[1, 2, 1, 2],
        [3, 4, 3, 4],
        [1, 2, 1, 2],
        [3, 4, 3, 4]])

当传入的参数少于需要复制的元素的维度时, 如果一个tensor的形状为(2, 2, 2)，传入tile中的参数为(2, 2)时, 会默认表示为(1, 2, 2)

In [55]:
x = torch.randn(2, 2, 2)
x

tensor([[[ 0.4555,  1.7824],
         [-0.7709, -0.0430]],

        [[-0.1933, -1.1088],
         [ 0.1955, -0.4354]]])

In [58]:
x.tile((2, 2))

tensor([[[ 0.4555,  1.7824,  0.4555,  1.7824],
         [-0.7709, -0.0430, -0.7709, -0.0430],
         [ 0.4555,  1.7824,  0.4555,  1.7824],
         [-0.7709, -0.0430, -0.7709, -0.0430]],

        [[-0.1933, -1.1088, -0.1933, -1.1088],
         [ 0.1955, -0.4354,  0.1955, -0.4354],
         [-0.1933, -1.1088, -0.1933, -1.1088],
         [ 0.1955, -0.4354,  0.1955, -0.4354]]])

使用tile和reshape代替repeat_interleave

In [60]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])  # shape: (2, 3)
torch.repeat_interleave(x, repeats=3, dim=0)

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [4, 5, 6],
        [4, 5, 6],
        [4, 5, 6]])

直接使用tile, 无法得到类似的结果

In [67]:
torch.tile(x, (3,))

tensor([[1, 2, 3, 1, 2, 3, 1, 2, 3],
        [4, 5, 6, 4, 5, 6, 4, 5, 6]])

In [68]:
torch.tile(x, (3,1))

tensor([[1, 2, 3],
        [4, 5, 6],
        [1, 2, 3],
        [4, 5, 6],
        [1, 2, 3],
        [4, 5, 6]])

In [69]:
# 需要使用 tile + reshape 才可以得到类似的结果
torch.tile(x, (3, )).reshape(6,3)

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [4, 5, 6],
        [4, 5, 6],
        [4, 5, 6]])